<a href="https://colab.research.google.com/github/heerakesavan/CE888-Data-Science-and-Decision-making/blob/Master/Lab%204/Lab_4_Recommender_Heera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [2]:

df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv', header=None)
df.head()

0      1      2      3      4    ...    96     97     98     99     100
0   74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1  100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2   49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3   48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4   91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60

[5 rows x 101 columns]

In [3]:
df.shape

(24983, 101)

In [4]:
df.describe()

0             1    ...           99            100
count  24983.000000  24983.000000  ...  24983.000000  24983.000000
mean      72.467478     34.401435  ...     55.753357     60.138090
std       21.859600     46.707059  ...     49.237139     47.913531
min       36.000000     -9.950000  ...     -9.950000     -9.950000
25%       53.000000     -0.150000  ...      1.335000      3.930000
50%       72.000000      5.050000  ...     99.000000     99.000000
75%      100.000000     99.000000  ...     99.000000     99.000000
max      100.000000     99.000000  ...     99.000000     99.000000

[8 rows x 101 columns]

In [5]:
df.isna().sum()

0      0
1      0
2      0
3      0
4      0
      ..
96     0
97     0
98     0
99     0
100    0
Length: 101, dtype: int64

**99 is the value that we need to replace with NaNs to ceate validation**

In [6]:
dfr = df.replace(99, np.nan)

In [7]:
dfr.isnull().sum()

0         81
1       8531
2       6799
3       8341
4       9375
       ...  
96     14613
97     14463
98     14317
99     14073
100    15040
Length: 101, dtype: int64

**Column 0 is the column we need to drop as it is not rating**

In [8]:
dfr.drop(columns=0, axis=1, inplace=True)

In [9]:
dfr.columns

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
             14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
             27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
             40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
             53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
             66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
             79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
             92,  93,  94,  95,  96,  97,  98,  99, 100],
           dtype='int64')

In [10]:
arr = dfr.values

In [11]:
arr.shape

(24983, 100)

In [12]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

2498300 (2498300,)


In [13]:

def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [14]:
new_arr, idx = replace(arr, 0.1)

In [15]:
arr[idx[0][0], idx[1][0]]

8.79

In [16]:
new_arr[idx[0][0], idx[1][0]]

99.0

**Latent factor**

In [17]:
n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [18]:

def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=10):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 5) == 0:
            print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [19]:
dfr = dfr.fillna(0)
dfr.head()

1     2     3     4     5     6    ...   95    96    97    98    99    100
0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...  0.00  0.00 -5.63  0.00  0.00  0.00
1  4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2  0.00  0.00  0.00  0.00  9.03  9.27  ...  0.00  0.00  0.00  0.00  0.00  0.00
3  0.00  8.35  0.00  0.00  1.80  8.16  ...  0.00  0.00  0.00  0.00  0.00  0.00
4  8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60

[5 rows x 100 columns]

In [20]:
ratings = dfr

In [21]:
#Fit StandardScaler into ratings
from sklearn.preprocessing import StandardScaler
ratings_ss = StandardScaler().fit_transform(ratings)
ratings_ss

array([[-1.99488279,  1.80864669, -2.23852141, ..., -0.09246592,
         0.00398848, -0.15816806],
       [ 0.8259334 , -0.09248732,  1.39449923, ...,  0.00345576,
        -1.25884825,  0.15572601],
       [-0.14120358, -0.03176828, -0.04782357, ..., -0.09246592,
         0.00398848, -0.15816806],
       ...,
       [-0.14120358, -0.03176828, -0.04782357, ..., -0.09246592,
         0.00398848, -0.15816806],
       [-0.14120358, -0.03176828, -0.04782357, ..., -0.09246592,
         0.00398848, -0.15816806],
       [ 0.43481183,  0.52726562, -0.95040922, ..., -0.09246592,
         0.00398848, -0.15816806]])

In [22]:
# Find the mean rating for all the jokes
mean_ratings = ratings_ss.mean(axis = 0) #axis of 0 for it to calculate mean across all rows 
print(mean_ratings.shape) #(150,) clearly indicates mean scores for all 150 jokes
mean_ratings

(100,)


array([-3.21383858e-17,  1.02032265e-17,  6.25703086e-18,  4.83497839e-18,
        1.35094984e-17, -5.63132777e-17, -1.32250879e-17, -7.67908332e-18,
        1.15186250e-17,  1.35806011e-17, -3.96041612e-17, -4.67144235e-17,
        4.27326766e-17, -2.61657654e-17,  1.25140617e-17,  4.21638557e-17,
       -9.42109760e-18,  1.20874460e-17, -1.27984722e-17, -1.13764197e-18,
       -3.72577746e-17,  3.69733641e-18, -1.47893457e-17,  5.54600462e-18,
       -1.73490401e-17, -3.13918082e-17,  5.81619459e-17, -1.05231883e-17,
       -1.06653935e-17, -2.84410493e-18,  7.82128857e-18, -4.77809629e-17,
        3.73288773e-17, -1.53581666e-17,  9.35710523e-17,  1.18741381e-16,
        6.64809528e-18,  2.38904814e-17,  2.51703287e-17,  1.22296512e-17,
        6.82585184e-18,  2.68767916e-17, -1.14475224e-17, -2.07619660e-17,
       -1.39361142e-17, -2.98631018e-17, -9.35710523e-17, -1.67091165e-17,
       -5.03406573e-17, -2.92942808e-17, -2.03353503e-17,  2.87254598e-17,
       -7.49777163e-17, -

In [23]:
#Convert array into Dataframe and rename column name for better readability
mean_ratings = pd.DataFrame(mean_ratings)
mean_ratings.rename(columns = {0: 'mean_joke_ratings'}, inplace = True) 
mean_ratings

mean_joke_ratings
0       -3.213839e-17
1        1.020323e-17
2        6.257031e-18
3        4.834978e-18
4        1.350950e-17
..                ...
95       1.663801e-17
96      -4.116842e-17
97      -2.801443e-17
98       1.329619e-17
99       3.377375e-17

[100 rows x 1 columns]

In [24]:
#Recommend the top n most popular jokes
n = 10
mean_ratings.sort_values(ascending = False, by = 'mean_joke_ratings')[:n] #outputs Joke ids and their mean ratings

mean_joke_ratings
35       1.187414e-16
34       9.357105e-17
60       9.044254e-17
90       6.427677e-17
71       5.972620e-17
93       5.887297e-17
26       5.816195e-17
57       5.631328e-17
80       4.863419e-17
12       4.273268e-17

In [25]:
mean_ratings.sort_values(ascending = True, by = 'mean_joke_ratings')[:n]

mean_joke_ratings
46      -9.357105e-17
53      -7.906612e-17
52      -7.497772e-17
64      -7.138703e-17
5       -5.631328e-17
61      -5.318476e-17
48      -5.034066e-17
88      -4.877640e-17
79      -4.806537e-17
31      -4.778096e-17

In [26]:
usercount = df[0].unique()

In [27]:
usercount

array([ 74, 100,  49,  48,  91,  47,  72,  36,  51,  53,  55,  50,  67,
        60,  54,  46,  38,  41,  73,  92,  89,  71,  40,  45,  62,  63,
        61,  65,  68,  69,  37,  56,  66,  64,  82,  57,  75,  88,  86,
        43,  83,  93,  94,  44,  59,  39,  58,  70,  78,  97,  90,  84,
        98,  96,  52,  80,  42,  81,  76,  79,  85,  77,  95,  87,  99])

In [28]:
meanr = ratings.mean()
min_idx = meanr.idxmin()
max_idx = meanr.idxmax()
print('Worst Joke ID predicted: ', min_idx, '; Average Rating: ', meanr[min_idx])
print('Best Joke ID predicted: ', max_idx, '; Average Rating: ', meanr[max_idx])

Worst Joke ID predicted:  16 ; Average Rating:  -3.1038238001841085
Best Joke ID predicted:  50 ; Average Rating:  3.663471160389066


In [29]:
df.iloc[9146, 67]

-0.34

In [30]:
items = pd.read_excel('https://github.com/albanda/CE888/blob/master/lab4-recommender/movies_latent_factors.xlsx?raw=true')
users = pd.read_excel('https://github.com/albanda/CE888/blob/master/lab4-recommender/movies_latent_factors.xlsx?raw=true', sheet_name=1)

In [31]:
items.head()

Movie ID  ...  Factor15
0        11  ... -0.248806
1        12  ...  1.274993
2        13  ... -0.419092
3        14  ... -0.681191
4        22  ... -2.292566

[5 rows x 17 columns]

In [32]:
items.shape

(100, 17)

In [33]:
users.head()

User   Factor1   Factor2   Factor3  ...  Factor12  Factor13  Factor14  Factor15
0  4768 -0.204024  0.161079 -0.090447  ...  0.355404  0.007108 -0.118663 -0.039125
1   156 -0.189652 -0.178979 -0.091490  ... -0.048606  0.045916  0.113671  0.179873
2  5323 -0.115308 -0.090886 -0.053129  ... -0.019460  0.108372  0.054471 -0.109552
3   174 -0.227462 -0.272532 -0.017231  ... -0.082396  0.036767 -0.165438  0.050692
4  4529 -0.014616 -0.102218 -0.107935  ... -0.132836 -0.039897  0.129063  0.102669

[5 rows x 16 columns]

In [34]:
users.set_index('User', inplace=True)

In [35]:
users.shape

(25, 15)

In [36]:
items.set_index('Movie ID', inplace=True)

In [37]:
Factor1 = items[["Title","Factor1"]].sort_values(by="Factor1",ascending=False)
Factor1.head(1)

Title   Factor1
Movie ID                                   
4327      Charlie's Angels (2000)  4.023815

In [40]:
def predict_rating(user, item):
  users1 = users.loc[user].values
  movie = items.loc[item].drop('Title').values
  return users1.dot(movie)

In [41]:
predict_rating(156,414)

-1.0237641229197594

In [42]:
predict_rating(525,3049)

-0.0422535108426401